web:
    image: nginx
    links:
     - dotclear:fpm
    volumes:
     - ./fpm/fpm.conf:/etc/nginx/conf.d/default.conf:Z
    volumes_from:
     - dotclear
    env_file:
     - ./.env
    restart: always
db:
    image: mysql
    volumes:
     - ./mysql/runtime:/var/lib/mysql
    restart: always
    env_file:
     - ./.env
dotclear:
    image: darknao/dotclear:fpm
    links:
     - db:mysqldb
    volumes:
     - ./data:/var/www/html
    restart: always
